import { StyleSheet } from 'react-native';
import { Colores } from './Colores';
import { Tamanos } from './Tamanos';

export const GlobalStyles = StyleSheet.create({
    container: {
        backgroundColor: Colores.colorFondo,
        minHeight: '100%',
        flex: 1,
        flexDirection: 'column',
        gap: 10,
    },
    imagenLogin: {
        width: 40,
        height: 40,
        marginRight: 15,
    },
    marginAjuste: {
        marginTop: 15,
    },
    lista: {
        padding: 10,
        margin: 10,
        borderRadius: 10,
        borderColor: Colores.colorBordePreview,
        borderWidth: 3,
        backgroundColor: Colores.colorFondoTarjeta,
        fontWeight: "bold"
    },
    imagenPerfil: {
        width: Tamanos.anchoFoto,
        height: Tamanos.alturaFoto,
        borderRadius: 10,
    },
    zonaPerfil: {
        flexDirection: 'row',
        gap: 15,
        margin: 25,
        marginTop: 15,
    },
    textoNormal: {
        fontFamily: 'Roboto2',
        fontSize: Tamanos.textoChico,
        color: Colores.textoNormal,
    },
    textoNegroNormal: {
        fontFamily: 'Roboto2',
        fontSize: Tamanos.textoNotificaciones,
        color: Colores.textoNegro,
    },
    textoNegroMediano: {
        fontFamily: 'Roboto2',
        fontSize: Tamanos.textoMediano,
        color: Colores.textoNegro,
    },
    textoAzulGrande: {
        fontFamily: 'WendyOne',
        fontSize: Tamanos.textoGrande,
        color: Colores.textoNormal,
        marginHorizontal: 25,
        marginTop: 5,
        marginBottom: -10,
    },
    textoAzulGrandeRoboto: {
        fontFamily: 'Roboto2',
        fontSize: Tamanos.textoGrande,
        color: Colores.textoNormal,
        marginHorizontal: 25,
        marginTop: -20,
        marginBottom: -10,
        textAlign: 'center',
    },
    textoPerfil: {
        color: Colores.blanco,
        fontSize: Tamanos.textoMediano,
    },
    textoNegrita: {
        fontWeight: 'bold',
    },
    textoSubrayado: {
        textDecorationLine: 'underline',
    },
    centradoVertical: {
        justifyContent: 'center',
    },
    notificacionCuadro: {
        backgroundColor: Colores.naranja,
        paddingTop: 15,
        borderWidth: 1,
        borderRadius: 10,
        marginHorizontal: 25,
        marginTop: -15,
    },
    notificacionCuadroTitulo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    fotoNotificacionFlecha: {
        width: 20,
        height: 11,
        marginRight: 20,
        marginTop: 5,
    },
    notificacion: {
        flexDirection: 'row',
        alignItems: 'center',
        borderTopWidth: 1,
        gap: 20,
        padding: 10,
    },
    textoNotificacionesTitulo: {
        flexShrink: 1, // se hace un poco más pequeño para que quepa la flecha
        fontFamily: "WendyOne",
        fontSize: Tamanos.textoMediano,
        color: Colores.textoBlanco,
        marginLeft: 10,
        paddingBottom: 15,
    },
    fotoNotificacion: {
        width: 40,
        height: 40,
    },
    enLinea: {
        flexDirection: 'row',
    },
    seccion: {
        flexDirection: 'row',
        marginHorizontal: 35,
        padding: 10,
        gap: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    seccionCuadro: {
        backgroundColor: Colores.stackBar,
        padding: 15,
        alignSelf: "center",
        borderRadius: 20,
        borderWidth: 1,
        marginBottom: 5,
    },
    imagenSeccion: {
        width: Tamanos.anchoFotoSeccion,
        height: Tamanos.alturaFotoSeccion,
    },
    
    footer: {
        backgroundColor: Colores.stackBar,
        padding: 20,
        alignItems: 'center',
    },
    centrar: {
        textAlign: 'center',
    },
    imagenFooter: {
        width: Tamanos.anchoFoto,
        height: Tamanos.alturaFoto,
        margin: 0,
    },
    drawerUserContainer: {
        backgroundColor: Colores.azulRgba,
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 0,
        marginBottom: 30,
        height: 200,
        borderRadius: 10,

    },
    drawerUserImg: {
        width: 100,
        height: 100,
        alignSelf: 'center',
        borderRadius: 50,
        marginBottom: 10,
        marginTop: 10,
    },
    cabezeraLoginRegistro: {
        alignItems: 'flex-end',
    },
    containerLogin: {
        backgroundColor: Colores.azulLogin,
        minHeight: '100%',
        flex: 1,
        flexDirection: 'column',
        gap: 5,
    },
    textoLoginTitulo: {
        fontFamily: "WendyOne",
        fontSize: Tamanos.textoTituloApp,
        color: Colores.textoBlanco,
        textAlign: 'center',
        padding: 10,
    },
    textoLoginSubTitulo: {
        fontFamily: "Roboto2",
        fontSize: Tamanos.textoMediano,
        color: Colores.textoBlanco,
        textAlign: 'center',
    },
    imagenLoginGrande: {
        width: 250,
        height: 200,
        marginRight: 15,
        marginTop: -40,
        alignSelf: 'center',
    },
    cuadroLogin: {
        backgroundColor: Colores.blanco,
        marginTop: 50,
        borderRadius: 30,
        paddingHorizontal: 20,
    },
    imagenPata: {
        width: 40,
        height: 40,
        marginLeft: 30,
        marginTop: 20,
    },
    imagenPataDerecha: {
        width: 40,
        height: 40,
        marginRight: 20,
        marginTop: -10,
        alignSelf: 'flex-end',
    },
    inputLogin: {
        backgroundColor: "#FDB672",
        width: "100%",
        height: 50,
        borderRadius: 25,
        textAlign: "left",
        justifyContent: "center",
        marginTop: 20,
    },
    inputLoginTexto: {
        color: "rgba(54, 98, 136, 0.84)",
        fontSize: 20,
    },
    textoBotonAcceder: {
        textAlign: "center",
        color: Colores.blanco,
        fontSize: 18,
        fontWeight: "bold",
    },
    botonAcceder: {
        width: "45%",
        height: 50,
        borderRadius: 25,
        backgroundColor: Colores.azulLogin,
        alignSelf: "center",
        justifyContent: "center",
        marginRight: "auto",
        marginVertical: 20,
    },
    negritaSubrayado:{
        fontWeight: "bold",
        textDecorationLine: "underline",
    },
    enlaceAcceso:{
        color: "rgba(54, 98, 136, 0.84)",
        fontSize: 17,
        fontFamily: "Roboto2",
    },
    enlaceAccesoBlanco:{
        color: Colores.textoBlanco,
        alignSelf: "center", 
        fontSize: 17,
        fontFamily: "Roboto2",
        paddingTop: 20
    },
    //
    containerComunidad: {
        flex: 1, 
        backgroundColor: Colores.blanco,
    },
    iconoCartel: {
        width: 40,
        height: 40,
    },
    tituloCartel: {
        color: Colores.textoNormal,
        fontSize: Tamanos.textoNotificacion,
        fontWeight: "bold",
        marginTop: -35,
        marginLeft: 50,
    },
    textoCartel: {
        fontSize: Tamanos.textoCartel,
        marginTop: 15,
        marginBottom: 0,
    },
    cartel: {
        width: "90%",
        backgroundColor: Colores.naranja,
        padding: 20,
        marginLeft: "5%",
        marginTop: 20,
        borderRadius: 10,
        marginBottom: 20,
    },
    flatListContent: {
        paddingBottom: 80, 
    },
    itemPosts: {
        width: "90%",
        backgroundColor: Colores.itemPost,
        height: 90,
        flex: 1,
        padding: 15,
        marginLeft: "5%",
        marginTop: 20,
        borderRadius: 10,
    },
    tituloPost: {
        fontSize: Tamanos.tituloPost,
        fontWeight: "bold",
        marginBottom: 10,
        color: Colores.textoNormal,
    },
    comentarioPeli: {
        fontSize: Tamanos.tituloPost,
        marginRight: 10,
        marginTop: -20,
        textAlign: "right",
    },
    bocadillo: {
        width: 27,
        height: 27,
        position: "absolute",
        right: 52,
        bottom: 10,
    },
    botonComunidad: {
        width: "30%",
        height: 50,
        borderRadius: 25,
        backgroundColor: Colores.azulRgba,
        alignSelf: "center",
        justifyContent: "center",
        position: "absolute",
        bottom: 20, 
    },
    textoBotonComunidad: {
        textAlign: "center",
        color: Colores.blanco,
        fontSize: Tamanos.textoMediano,
    },

    //
    containerRefugio: {
        backgroundColor: Colores.blanco,
    },
    zonaBuscador: {
        flexDirection: "row",
        width: "100%",
        marginBottom: 20,
    },
    buscador: {
        width: "75%",
        height: 50,
        borderColor: Colores.azulRgba,
        borderWidth: 2,
        borderRadius: 10,
    },
    textoBuscador: {
        marginLeft: 10,
        marginTop: "1.5%",
    },
    buscadorPequeño: {
        marginTop: 20,
        marginLeft: 10,
        width: "12%",
        height: 50,
        borderColor: Colores.azulRgba,
        borderWidth: 2,
        borderRadius: 10,
    },
    iconoBuscador: {
        width: 30,
        height: 30,
        marginLeft: 7,
        marginTop: 7,
    },
    cartelInfo: {
        width: "90%",
        backgroundColor: Colores.azulRgba,
        borderRadius: 10,
        padding: 10,
    },
    cartelInfoTitulo: {
        color: Colores.blanco,
        fontSize: Tamanos.textoNotificacion,
        fontWeight: "bold",
    },
    cartelInfoTexto: {
        color: Colores.blanco,
        fontSize: Tamanos.cartelInfoTexto,
        marginTop: 10,
        marginBottom: -10,
    },
    cartelRefugio: {
        width: "100%",
        height: 100,
        resizeMode: "contain",
        marginTop: 5,
        marginBottom: -30,
    },
    textoCategorias: {
        color: Colores.azulRgba,
        fontSize: 19,
    },
    textoVerTodo: {
        color: Colores.azulRgba,
        fontSize: Tamanos.tituloPost,
        marginTop: -25,
        marginLeft: "75%",
        textDecorationLine: "underline",
    },
    seccionRefugio: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: "3%",
    },
    seccionCuadroRefugio: {
        backgroundColor: Colores.naranja,
        borderRadius: 20,
        height: 110,
        width: 110,
        alignItems: "center",
        justifyContent: "center",
        margin: 10,
        marginBottom: 30,
    },
    textoFiltroRefugio: {
        fontSize: Tamanos.textoNotificaciones,
        color: Colores.azulRgba,
        fontWeight: "bold",
        textAlign: "center",
        marginTop: 5,
    },
    seccionPerros: {
        paddingBottom: 20,
        backgroundColor: Colores.blanco,
    },
    itemPerros: {
        backgroundColor: Colores.naranja,
        borderRadius: 10,
        padding: 10,
        width: "40%",
        marginRight: 0,
        marginBottom: 20,
        marginLeft: 25,
    },
    imagenPerro: {
        width: "100%",
        height: 100,
        marginBottom: 10,
    },
    nombrePerro: {
        fontSize: Tamanos.textoCartel,
        fontWeight: "bold",
        color: Colores.azulRgba,
    },
    infoPerro: {
        color: "rgba(54, 98, 136, 0.84)",
        fontSize: Tamanos.textoNotificaciones,
        marginBottom: 10,
    },
    detallesPerro:{
        textDecorationLine: "underline",
    },
    imagenSeccionRefugio: {
        width: 60, 
        height: 60,
        resizeMode: "contain",
        marginBottom: 5,
    },
    favorito:{
        width: 25,
        height: 25,
    },
    mapa: {
        marginTop: "-15%",
        width: "100%",   
        height: "60%",   
    },
    containerMapa: {
        width: "100%",
        height: "100%",  
        flex: 1,         
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: Colores.azulRgba,
    },
    
    zonaBuscadorRescate: {
        flexDirection: "row",
        width: "100%",
    },
    buscadorRescate: {
        width: "75%",
        height: 50,
        backgroundColor: Colores.blanco,
        borderRadius: 10,
    },
    textoBuscadorRescate: {
        marginLeft: 10,
        marginTop: "1.5%",
    },
    buscadorPequeñoRescate: {
        marginTop: 20,
        marginLeft: 10,
        width: "12%",
        height: 50,
        backgroundColor: Colores.blanco,
        borderRadius: 10,
    },
    iconoBuscadorRescate: {
        width: 30,
        height: 30,
        marginLeft: 9,
        marginTop: 7,
    },
    espacioSituacion:{
        backgroundColor: Colores.blanco,
        width: "90%",
        height: 140,
        marginTop: 20,
        borderRadius: 10,
    },
    espacioSituacionTexto:{
        fontSize: 15,
        color: Colores.azulRgba,
        marginLeft: 10,
        marginTop: "1.5%",
    },
    
    botonRescate:{
        width: "27%",
        height: "7%",
        marginTop: "-7%",
        borderRadius: 30,
        backgroundColor: Colores.blanco,
    },
    textoBotonRescate:{
        textAlign: "center",
        marginTop: 13,
        fontWeight: "bold",
    },
    //
    containerPerro: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colores.naranja,
        padding: 20,
    },
    botonPerro:{
        width: "95%",
        height: 50,
        borderRadius: 25,
        backgroundColor: Colores.azulRgba,
        alignSelf: "center",
        justifyContent: "center",
        position: "absolute",
        bottom: 100, 
    },
    textoBotonPerro: {
        textAlign: "center",
        color: Colores.blanco,
        fontSize: Tamanos.textoMediano, 
    },
    botonFavoritoPerro:{
        position: "absolute",
        top: "43%",
        right: "10%",
    },
    favoritoPerro:{
        width: 35,
        height: 35,
    },
    contenedorIcono:{
        backgroundColor: Colores.naranja,
        height: 50,
        width: 50,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
    },
    punto:{
        width: 18,
        backgroundColor: Colores.azulRgba,
        height: 18,
        borderRadius: 100,
        marginLeft: "47%",
    },
    nombreEncargada:{
        fontWeight: 'bold',
    },
    nombreProtectora:{
        fontSize: Tamanos.espacioSituacionTexto,
        fontWeight: 'bold',
        color: Colores.azulRgba,
    },
    descripcion:{
        fontSize: Tamanos.espacioSituacionTexto,
        color: Colores.azulRgba,
        marginTop: 20,
    },
    fotoEncargada:{
        width: 70,
        height: 70,
        borderRadius: 100,
    },
    tarjeta: {
        backgroundColor: Colores.blanco,
        padding: 20,
        borderRadius: 10,
        shadowColor: Colores.textoNegro,
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        width: '100%',
        height: "80%",
        marginBottom: 160,
    },
    image: {
        width: "100%",
        height: 200,
        marginBottom: 20,
        borderRadius: 10,
    },
    pin:{
        width: 25,
        height: 25,
        marginRight: 10,  
    },
    ciudad:{
        marginBottom: 10,
        marginLeft: -5,
    },
    contenedorInfo:{
        flexDirection: 'row',
        gap: 10,
        marginTop: 10,
        justifyContent: "center"
    },
    contenedorTexto:{
        fontSize: Tamanos.textoNotificaciones,
        fontWeight: 'bold',
        color: Colores.azulRgba,
    },
    name: {
        fontSize: Tamanos.name,
        fontWeight: 'bold',
        color: Colores.azulRgba,
        marginBottom: 10,
    },
    info: {
        fontSize: Tamanos.textoNotificacion,
        color: Colores.gray,
    },
    errorText: {
        fontSize: Tamanos.textoNotificacion,
        color: Colores.red,
    },
    
    contenedorCiudad:{
        flexDirection: 'row',
    },
    contenedorInfoPequeño:{
        flexDirection: 'column',
        backgroundColor: Colores.naranja,
        width: 90,
        height: 80,
        borderRadius: 10,
        padding: 5,
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    contenedorProtectora:{
        flexDirection: "row",
        gap: 10,
        alignItems: "center",
    },
    //
    containerRegistro: {
        backgroundColor: Colores.blanco,
        flex: 1,
    },
    logo: {
        width: 50,
        height: 50,
        margin: 15,
        marginBottom: 0,
        marginLeft: "auto",
    },
    marginAuto: {
        marginLeft: "auto",
        marginRight: "auto",
    },
    bienvenida: {
        fontWeight: "bold",
    },
    titulo: {
        fontFamily: "WendyOne",
        fontSize: Tamanos.textoTituloApp,
        color: Colores.azulRgba,
        textAlign: 'center',        
    },
    animales:{
        flexDirection: "row",
    },
    perrito:{
        width: 150,
        height: 110,
        position: "absolute",
        top: 20,
        left: 90,
    },
    gatito:{
        width: 130,
        height: 110,
        position: "absolute",
        top: 20,
        left: 180,
    },
    contenedor: {
        alignItems: "center",
        backgroundColor: Colores.azulRgba,
        padding: 20,
        marginTop: 130,
        width: "100%",
        height: "60%",
        borderRadius: 40,
    },
    slogan:{
        color: Colores.blanco,
        fontSize: Tamanos.slogan,
        fontWeight: "bold",
        marginTop: -15,
    },
    huellaCompartido:{
        width: 55,
        height: 55,
    },
    huella:{
        marginRight: "auto",
    },
    huella2:{
        marginLeft: "auto",
        transform: [{ rotate: "50deg" }],
        marginBottom: -20,
        marginTop: -10,
    },
    cuadro:{
        backgroundColor: Colores.naranja,
        width: "100%",
        height: 50,
        borderRadius: 25,
        textAlign: "left",
        justifyContent: "center",
        marginTop: 20,
    }, 
    textoBotonRegistro:{
        textAlign: "center",
        color: Colores.azulRgba,
        fontSize: Tamanos.textoNotificacion,
        fontWeight: "bold",
    },
    botonRegistro:{
        width: "45%",
        height: 50,
        borderRadius: 25,
        backgroundColor: Colores.blanco,
        alignSelf: "center",
        justifyContent: "center",
        marginRight: "auto",
        marginTop: 30,
    },
    login:{
        flexDirection: "row",
        alignItems: "center",
        marginTop: 20,
        gap: 30,
    },
    pregunta:{
        color: Colores.azulRgba,
        fontSize: Tamanos.cartelInfoTexto,
    },
    azulTextoMediano:{
        color: Colores.azulRgba,
        fontSize: Tamanos.textoMediano,
    },
    marginLeft20:{
        marginLeft: 20,
    },
    marginLeftTop20:{
        marginLeft: 20,
        marginTop:20,
    },
    customToastContainer: {
        backgroundColor: Colores.azulLogin,
        padding: 15,
        borderRadius: 10,
        marginHorizontal: 10,
        marginTop: 20,
        alignItems: "center",
    },
    toastTitle: {
        fontSize: Tamanos.textoNotificacion,
        fontWeight: "bold",
        color: Colores.blanco,
    },
    toastMessage: {
        fontSize: Tamanos.textoNotificaciones,
        color: Colores.blanco,
        marginTop: 5,
    },
    infoRescate:{
        width: 30,
        height: 30,
        marginRight: "80%",
        marginTop: "5%",
    }
});
