export const Tamanos = {
    weightMediano: 300,
    weightGrande: 400,
    textoTituloApp: 45,
    textoTitulo: 35,
    textoGrande: 30,
    textoMediano: 20,
    textoChico: 12,
    textoNotificacion: 18,
    alturaFoto: 90,
    anchoFoto: 90,
    alturaFotoSeccion: 50,
    anchoFotoSeccion: 50,
    textoNotificaciones: 14,
}as const;